### ISSUE TITLE
example page ?

### ISSUE THREAD

**Issue by souhaiebtar** [Mazurco066/react-native-settings-page#1]
would you please publish the example on github,
thanks anyway

**Comment by Mazurco066** [comment]
oK, i ll try to publish the example this week.

**Comment by Mazurco066** [comment]
I added a example project ate the repository, if you need more info about the usage read https://github.com/Mazurco066/react-native-settings-page, follow the Get Started section and nothing ll go wrong :). The example project is named 'app' at the repository root
